version: '3'
services:
  iot-agent:
    image: 'diwise/iot-agent:latest'
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    restart: always
    depends_on:
      - rabbitmq
      - iot-core
      - iot-device-mgmt
    environment:
      MQTT_HOST: $MQTT_HOST
      MQTT_PORT: $MQTT_PORT
      MQTT_TOPIC_0: $MQTT_TOPIC_0
      MQTT_TOPIC_1: $MQTT_TOPIC_1
      MQTT_USER: $MQTT_USER
      MQTT_PASSWORD: $MQTT_PASSWORD
      RABBITMQ_HOST: 'rabbitmq'
      DEV_MGMT_URL: 'http://iot-device-mgmt:8080'
      #OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
    ports:
      - '8080'


  iot-core:
    image: 'ghcr.io/diwise/iot-core@sha256:c4b69010e44f12a1043749244ed52d43ae8a298e9955a0b4480c7b778b53491b'
    restart: always
    environment:
      RABBITMQ_HOST: 'rabbitmq'
      #OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'


  iot-device-mgmt:
    image: 'ghcr.io/diwise/iot-device-mgmt@sha256:74a4042e76cab9c4b3e75c8e4360f63cbc0cabf6251ce84aab0dbe74ea6ca1a8'
    restart: always
    environment:
      RABBITMQ_HOST: 'rabbitmq'
      #OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4318'
    ports:
      - '8080'


  rabbitmq: 
    image: 'bitnami/rabbitmq:3.8'
    #image: 'arm64v8/rabbitmq:3.8'
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'bitnami'
    ports:
      - '4369'
      - '5672'
      - '25672'
      - '15672'
    volumes:
      - 'rabbitmq_data:/bitnami'


volumes:
  rabbitmq_data:
    driver: local
