version: '3'
services:
  rabbitmq:
    image: 'bitnami/rabbitmq:3.8'
    #image: 'arm64v8/rabbitmq:3.8'
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'bitnami'
    expose:
      - "5672"
    ports:
      - '4369'
      - '5672:5672'
      - '25672'
      - '15672'
    volumes:
      - 'rabbitmq_data:/bitnami'

  keycloak:
    image: quay.io/keycloak/keycloak:19.0
    command:
    - 'start-dev'
    - '--hostname=iam.diwise.local'
    - '--hostname-port=8444'
    - '--proxy=edge'
    - '--health-enabled=true'
    - '-Dkeycloak.migration.action=import'
    - '-Dkeycloak.migration.provider=singleFile'
    - '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING'
    - '-Dkeycloak.migration.file=/application-realm.json'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8080:8080'
      - '8444:8444'
      - '8443:8443'
    volumes:
     - ./configs/keycloak/realm.json:/application-realm.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 5s
      timeout: 5s
      retries: 24
      start_period: 10s

volumes:
  rabbitmq_data:
    driver: local
