version: '3'
services:
  iot-agent:
    image: 'diwise/iot-agent:latest'
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    restart: always
    depends_on:
      - rabbitmq
    environment:
      MQTT_HOST: $MQTT_HOST
      MQTT_PORT: $MQTT_PORT
      MQTT_TOPIC_0: $MQTT_TOPIC
      MQTT_USER: $MQTT_USER
      MQTT_PASSWORD: $MQTT_PASSWORD
      RABBITMQ_HOST: 'rabbitmq'
    ports:
      - '8080'


  iot-device-mgmt:
    image: 'ghcr.io/diwise/iot-device-mgmt@sha256:f7ebb43e577584142c1f97ed84b941465ab1d3e368d1ef3b89a87bf7a361aa30'
    ports:
      - '8080'


  rabbitmq: 
    image: 'bitnami/rabbitmq:3.8'
    ports:
      - '4369'
      - '5672'
      - '25672'
      - '15672'
    volumes:
      - 'rabbitmq_data:/bitnami'


volumes:
  rabbitmq_data:
    driver: local
