version: '3'
services:
  iot-agent:
    image: 'diwise/iot-agent:latest'
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    restart: always
    depends_on:
      - rabbitmq
    environment:
      MQTT_HOST: $MQTT_HOST
      MQTT_PORT: $MQTT_PORT
      MQTT_TOPIC_0: $MQTT_TOPIC_0
      MQTT_TOPIC_1: $MQTT_TOPIC_1
      MQTT_USER: $MQTT_USER
      MQTT_PASSWORD: $MQTT_PASSWORD
      RABBITMQ_HOST: 'rabbitmq'
      DEV_MGMT_URL: 'http://iot-device-mgmt:8080'
    ports:
      - '8080'


  iot-core:
    image: 'ghcr.io/diwise/iot-core@sha256:1907446b181214983989e6cd376248b948a7d93ddd168fc440d17ec582349053'
    environment:
      RABBITMQ_HOST: 'rabbitmq'


  iot-device-mgmt:
    image: 'ghcr.io/diwise/iot-device-mgmt@sha256:b22be97b6b15e74d77b952a8a00d80ffb23fa7522c54d0b599d8d55317cb887c'
    ports:
      - '8080'


  rabbitmq: 
    image: 'rabbitmq:3.8'
    #image: 'arm64v8/rabbitmq:3.8'
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'bitnami'
    ports:
      - '4369'
      - '5672'
      - '25672'
      - '15672'
    volumes:
      - 'rabbitmq_data:/bitnami'


volumes:
  rabbitmq_data:
    driver: local
