version: '3'
services:
  iot-agent:
    image: 'diwise/iot-agent:latest'
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    restart: always
    depends_on:
      - rabbitmq
      - iot-core
      - iot-device-mgmt
    environment:
      MQTT_HOST: $MQTT_HOST
      MQTT_TOPIC_0: $MQTT_TOPIC_0
      MQTT_USER: $MQTT_USER
      MQTT_PASSWORD: $MQTT_PASSWORD
      DEV_MGMT_URL: 'http://iot-device-mgmt:8080'
      MSG_FWD_ENDPOINT: 'http://iot-agent:8080/api/v0/messages'
      RABBITMQ_HOST: 'rabbitmq'
    ports:
      - '8080'

  iot-core:
    image: 'ghcr.io/diwise/iot-core:prod-2c7bde63b1a409d5d773e139f9d81f89cb9af702'
    restart: always
    environment:
      DEV_MGMT_URL: 'http://iot-device-mgmt:8080'
      RABBITMQ_HOST: 'rabbitmq'

  iot-device-mgmt:
    image: 'ghcr.io/diwise/iot-device-mgmt:prod-2079682e52692648424604f30478fe4c589c02d6'
    restart: always
    environment:
      RABBITMQ_HOST: 'rabbitmq'
    volumes:
      - ./configs/diwise/devices.csv:/opt/diwise/config/devices.csv
    ports:
      - '8080'

  rabbitmq: 
    image: 'bitnami/rabbitmq:3.8'
    #image: 'arm64v8/rabbitmq:3.8'
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'bitnami'
    ports:
      - '4369'
      - '5672'
      - '25672'
      - '15672'
    volumes:
      - 'rabbitmq_data:/bitnami'

volumes:
  rabbitmq_data:
    driver: local
